"""Shared pipeline defaults."""

from __future__ import annotations

# Featurize
N_HASH_DIMS = 256
MIN_DOMAIN_FREQ = 3

# Atlas / novelty
PCA_N_COMPONENTS = 50
DEFAULT_NOVELTY_K = 5

# Temporal holdout
DEFAULT_TEMPORAL_CUTOFF = "2022-09-16"
# Excluded in the non-major-family temporal subset
MAJOR_FAMILIES = ("PKS", "NRPS", "hybrid")

# ESM
DEFAULT_ESM_MODEL = "facebook/esm2_t33_650M_UR50D"
LEGACY_ESM_MODEL = "facebook/esm2_t30_150M_UR50D"
DEFAULT_ESM_POOLING = "length_weighted"  # mean | length_weighted
DEFAULT_ESM_MAX_AA = 1024
DEFAULT_ESM_MAX_PROTEINS = 80
DEFAULT_ESM_BATCH_TOKENS = 6000

# Contrastive encoder
DEFAULT_ENCODER_HIDDEN = 512
DEFAULT_ENCODER_EMBED_DIM = 256
DEFAULT_ENCODER_PROJ_DIM = 128
DEFAULT_ENCODER_POOLING = "attention"  # attention | mean | deepsets
DEFAULT_ENCODER_OBJECTIVE = "simclr"  # simclr | supcon
DEFAULT_ENCODER_EPOCHS = 40
DEFAULT_ENCODER_BATCH_SIZE = 64
DEFAULT_ENCODER_LR = 1e-3
DEFAULT_ENCODER_TEMPERATURE = 0.1
DEFAULT_ENCODER_KEEP_FRAC = 0.7  # protein-subset augmentation
DEFAULT_ENCODER_FEAT_DROPOUT = 0.1
DEFAULT_ENCODER_MAX_PROTEINS = 80
DEFAULT_ENCODER_SEED = 42
